# Generated by Django 4.1.13 on 2024-07-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_contact_alter_news_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
